local icons = {
  hl = {
    bug = "",
    bug_alt = "",
    error = "",
    hint = "",
    info = "",
    warn = "",
    install = "",
    pending = "",
    uninstall = "",
  },
	vs = {
		Array = " ",
		Boolean = " ",
		Class = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Enum = " ",
		EnumMember = " ",
		Event = "󱐌 ",
		Field = " ",
		File = " ",
		Folder = " ",
		Function = " ",
		Key = " ",
		Keyword = "󰌋 ",
		Interface = " ",
		Namespace = " ",
		Null = "󰢤 ",
		Number = " ",
		Method = " ",
		Module = "󰏗 ",
		Object = " ",
		Operator = " ",
		Package = " ",
		Property = " ",
		Reference = " ",
		Snippet = " ",
		String = " ",
		Struct = " ",
		Text = " ",
		TypeParameter = " ",
		Unit = " ",
		Variable = " ",
		Value = "󰎠 ",
	},
}

return icons
