local opt = vim.opt

opt.expandtab = true                                     -- Convertir tabulaciones en espacios
opt.shiftwidth = 2                                       -- Número de espacios insertados de sangría
opt.smartindent = true                                   -- Insertar sangría automáticamente
opt.smartcase = true                                     -- No ignora el caso con mayúsculas
opt.ignorecase = false                                   -- Ignorar mayúsculas y minúsculas en las búsquedas
opt.encoding = "utf-8"                                   -- Define la codificación
opt.guifont = "Victor Mono:h15"                          -- Define la fuente para las apps
opt.pumheight = 10                                       -- Altura del menú emergente
opt.background = "light"
opt.conceallevel = 0                                     -- Permite que `` sea visible en markdown
opt.cursorcolumn = false                                 -- Desactiva el resaltado del cursor
opt.cursorline = true                                    -- Resalta la línea actual
opt.fillchars = "eob: "
opt.foldenable = false
opt.list = true                                          -- Muestra algunos caractares invisibles
opt.listchars = "eol:↩,trail:·,lead:·,tab:.."
opt.mouse = "a"                                          -- Permite usar mouse
opt.number = true                                        -- Mostrar líneas numeradas
opt.relativenumber = true                                -- Mostrar líneas numeradas relativas
opt.showmode = false                                     -- Oculta -- INSERTAR
opt.termguicolors = true                                 -- Permite los colores de ui
opt.title = true                                         -- Establecer el título de la ventana
opt.wrap = false                                         -- Mostrar líneas como una línea larga
opt.backup = false                                       -- Crea un archivo de copia de seguridad
opt.clipboard = "unnamedplus"                            -- Permite acceder al portapapeles del sistema
opt.hidden = true                                        -- Habilitar búferes modificados en segundo plano
opt.laststatus = 3                                       -- Establece solo 1 línea de estado
opt.iskeyword = "@,48-57,_,192-255,-"
opt.splitbelow = true                                    -- Obligar a todas las divisiones horizontales a ir debajo
opt.splitright = true                                    -- Obligar a todas las divisiones verticales a ir a la derecha
-- opt.spell = true
opt.spelllang = "en,es"
opt.swapfile = false                                     -- Crea un archivo de intercambio
opt.scrolloff = 6                                        -- Número mínimo de líneas encima y debajo del cursor
opt.sidescrolloff = 6                                    -- Número mínimo de líneas izquierda y derecha del cursor
opt.undofile = true                                      -- Habilitar deshacer persistente
opt.writebackup = false                                  -- Habilita archivos protegidos para que no se edite 2 veces
opt.whichwrap = "b,s,<,>,[,],h,l"
opt.timeoutlen = 300                                     -- Tiempo de espera para que se complete una secuencia mapeada
opt.updatetime = 300                                     -- Finalización más rápida
opt.winwidth = 10
opt.winminwidth = 10
opt.equalalways = false
opt.shortmess:append("sI")                              -- Elimina los mensajes al inicio
opt.shortmess = opt.shortmess + { c = true }
