local icons = {
  bl = {
    indicator = "▎",
    buffer_close = "",
    modified = "●",
    close = "",
    left = "",
    right = "",
  },
  dg = {
    hint = "",
    hintf = "",
    bug = "",
    bugf = "",
    info = "",
    infof = "",
    warning = "",
    warningf = "",
    error = "",
    errorf = "",
  },
  gl = {
    default = "",
    zdefault = "",
    symlink = "",
    bookmark = "",
  },
  fl = {
    arrow_open = "",
    arrow_closed = "",
    default = "",
    defaultf = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
    symlink_open = "",
  },
  gt = {
    unstaged = "✗",
    staged = "✓",
    unmerged = "",
    renamed = "",
    untracked = "",
    deleted = "⊟",
    deletedf = "",
    ignored = "◌",
  },
  vs = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Key = " ",
    Keyword = " ",
    Interface = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Method = " ",
    Module = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Variable = " ",
    Value = " ",
  },
  st = {
    edit = " ",
    readonly = "  ",
    readonlyf = "  ",
    unmerged = "  ",
    unmergedf = "  ",
    zunmerged = "  ",
    add = "  ",
    change = "  ",
    deleted = "  ",
    lsp_client = " ",
    gear = " ",
    terminal = "  ",
    line_number = "  ",
    line_percent = "  ",
    sbar = { "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" },
    sbar2 = { "🭶", "🭷", "🭸", "🭹", "🭺", "🭻" },
    spinners = {
      "⠋",
      "⠙",
      "⠹",
      "⠸",
      "⠼",
      "⠴",
      "⠦",
      "⠧",
      "⠇",
      "⠏",
    },
  },
  os = {
    linux = "", -- 
    macos = "",
    windows = "",
  },
  sp = {
    block = "█",
    left = "",
    right = "",
    left_fill = "",
    right_fill = "",
    slant_left = "",
    slant_right = "",
    slant_right2 = "",
    slant_left2 = "",
    left_round = "",
    right_round = "",
    left_roundt = "",
    right_roundt = "",
  },
}

return icons
