return {
  "lukas-reineke/indent-blankline.nvim",
  main = "ibl",
  event = { "BufReadPost", "BufNewFile", "BufWritePre" },
  opts = {
    enabled = true,
    indent = {
      char = "▎",
    },
    scope = {
      enabled = true,
      char = "▏",
      show_start = true,
      show_end = false,
      injected_languages = true,
      highlight = "IblScope",
      include = {
        node_type = {
          ["*"] = {
            "argument_list",
            "arguments",
            "assignment_statement",
            "Block",
            "chunk",
            "class",
            "ContainerDecl",
            "dictionary",
            "do_block",
            "do_statement",
            "element",
            "except",
            "FnCallArguments",
            "for",
            "for_statement",
            "function",
            "function_declaration",
            "function_definition",
            "if_statement",
            "IfExpr",
            "IfStatement",
            "import",
            "InitList",
            "jsx_self_closing_element",
            "list_literal",
            "method",
            "object",
            "ParamDeclList",
            "repeat_statement",
            "return_statement",
            "selector",
            "SwitchExpr",
            "table",
            "table_constructor",
            "try",
            "tuple",
            "type",
            "var",
            "while",
            "while_statement",
            "with",
          },
        },
      },
      exclude = {
        language = { "fish", "yaml" },
      },
    },
    exclude = {
      filetypes = {
        "lazy",
        "mason",
        "notify",
        "NvimTree",
        "spectre_panel",
        "markdown",
        "text",
      },
    },
  },
}
