return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    {
      "nvim-treesitter/nvim-treesitter-context",
      opts = { max_lines = 5 }
    },
    { "HiPhish/rainbow-delimiters.nvim" },
    { "nvim-treesitter/nvim-treesitter-textobjects" },
  },
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile", "BufWritePre" },
  opts = {
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "glimmer",
      "go",
      "hlsplaylist",
      "html",
      "http",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "latex",
      "lua",
      "luadoc",
      "markdown",
      "markdown_inline",
      "perl",
      "php",
      "phpdoc",
      "python",
      "requirements",
      "robot",
      "rst",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "xml",
      "yaml",
    },
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "g+",
        node_incremental = "g+",
        scope_incremental = false,
        node_decremental = "g-",
      },
    },
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
        keymaps = {
          ["af"] = "@function.outer",
          ["if"] = "@function.inner",
          ["ab"] = "@statement.outer",
          ["ib"] = "@statement.inner",
          ["ac"] = "@class.outer",
          ["ic"] = { query = "@class.inner", desc = "Select inner part of a class region" },
          ["as"] = { query = "@scope", query_group = "locals", desc = "Select language scope" },
        },
        include_surrounding_whitespace = true,
      },
      move = {
        enable = true,
        set_jumps = true,
        goto_next_start = {
          ["<a-}>"] = { query = "@function.outer", desc = "Next method/function def start" },
          ["]c"] = { query = "@class.outer", desc = "Next class start" },
        },
        goto_previous_start = {
          ["<a-{>"] = { query = "@function.outer", desc = "Prev method/function def start" },
          ["[c"] = { query = "@class.outer", desc = "Prev class start" },
        },
      },
    }
  },
  config = function(_, opts)
    require("nvim-treesitter.configs").setup(opts)
  end,
  keys = {
    { "g+", desc = "Increment Selection" },
    { "g-", desc = "Decrement Selection", mode = "x" },
  },
}
